# Generated by Django 4.2.3 on 2024-01-02 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 2, 0, 14, 28, 922879, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
