# Generated by Django 5.0 on 2023-12-28 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_alter_post_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
