# Generated by Django 4.2.3 on 2024-01-02 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rate",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 2, 1, 37, 17, 411725, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
