# Generated by Django 5.0 on 2023-12-28 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_disposablecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="code",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 28, 4, 37, 37, 377439, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
