# Generated by Django 4.2.3 on 2024-01-02 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0005_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="rate",
            field=models.IntegerField(
                choices=[(1, "1"), (1, "2"), (3, "3"), (4, "4"), (5, "5")], default="0"
            ),
        ),
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 2, 2, 16, 31, 379463, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
