# Generated by Django 5.0 on 2023-12-28 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0005_alter_disposablecode_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="code",
            field=models.CharField(default="asdfasdf", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 28, 4, 38, 57, 380926, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
