# Generated by Django 4.2.3 on 2024-01-02 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0006_alter_comment_rate_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="rate",
        ),
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 2, 3, 24, 6, 531717, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
