# Generated by Django 5.0 on 2023-12-28 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0007_alter_disposablecode_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 28, 4, 39, 38, 24754, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
