# Generated by Django 4.2.3 on 2024-01-04 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0008_alter_disposablecode_expires_at_communities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 4, 1, 55, 28, 145909, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
