# Generated by Django 5.0 on 2023-12-28 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0008_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 28, 4, 44, 27, 191602, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
