# Generated by Django 4.2.3 on 2024-01-04 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0011_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 4, 5, 31, 3, 52459, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
