# Generated by Django 5.0 on 2024-01-05 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0012_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 5, 6, 27, 39, 606470, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
